// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByJLOvdy6HzdS9IViCgyUMQ5bF9Fm_v68',
    appId: '1:252364513765:web:389874e6587b0c9feb8f0c',
    messagingSenderId: '252364513765',
    projectId: 'spadarstva-ce2f4',
    authDomain: 'spadarstva-ce2f4.firebaseapp.com',
    storageBucket: 'spadarstva-ce2f4.appspot.com',
    measurementId: 'G-W18PTRRYYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbpOeO5mB_RguvT1vh9MfEWnrxAxNgSQY',
    appId: '1:252364513765:android:3418aaee201b6701eb8f0c',
    messagingSenderId: '252364513765',
    projectId: 'spadarstva-ce2f4',
    storageBucket: 'spadarstva-ce2f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuN03tmDlwl1zuqeeXTbTlG_tFDDF6LxQ',
    appId: '1:252364513765:ios:b816b5249f2ab866eb8f0c',
    messagingSenderId: '252364513765',
    projectId: 'spadarstva-ce2f4',
    storageBucket: 'spadarstva-ce2f4.appspot.com',
    iosBundleId: 'com.spadarstva.spadarstva',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuN03tmDlwl1zuqeeXTbTlG_tFDDF6LxQ',
    appId: '1:252364513765:ios:59bf5b97520c797aeb8f0c',
    messagingSenderId: '252364513765',
    projectId: 'spadarstva-ce2f4',
    storageBucket: 'spadarstva-ce2f4.appspot.com',
    iosBundleId: 'com.spadarstva.spadarstva.RunnerTests',
  );
}
